import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SessionWrapper from "@/components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const name = process.env.NEXT_PUBLIC_APP_NAME || "BenQ";
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 text-gray-900">
        <SessionWrapper>
          <nav className="sticky top-0 z-10 bg-white/80 backdrop-blur border-b">
            <div className="mx-auto max-w-4xl px-4 py-3 flex items-center gap-4">
              <span className="font-extrabold">{name}</span>
              <ul className="flex gap-4 text-sm">
                <li>
                  <Link href="/quiz">Quiz</Link>
                </li>
                <li>
                  <Link href="/calendar">Calendar</Link>
                </li>
                <li>
                  <Link href="/match">Match</Link>
                </li>
                <li>
                  <Link href="/leaderboard">Leaderboard</Link>
                </li>
              </ul>
            </div>
          </nav>
          <main className="mx-auto max-w-4xl px-4 py-6">{children}</main>
        </SessionWrapper>
      </body>
    </html>
  );
}
